Update msbuild.yml

diff --git a/.github/workflows/msbuild.yml b/.github/workflows/msbuild.yml
--- a/.github/workflows/msbuild.yml
+++ b/.github/workflows/msbuild.yml
@@ -56,12 +56,20 @@ jobs:
         run: |
           Get-ChildItem -Path "output/x64/Release" -Recurse -Force || echo "Output directory does not exist."
 
-      # Step 9: Archive the built DLL
+      # Step 9: Check if the DLL was built
+      - name: Check for DLL existence
+        run: |
+          if (!(Test-Path "output/x64/Release/SEOwnedDEx64Release.dll")) {
+              Write-Error "The DLL was not found at the expected path."
+              exit 1
+          }
+
+      # Step 10: Archive the built DLL
       - name: Archive build output
         run: |
           Compress-Archive -Path "output/x64/Release/SEOwnedDEx64Release.dll" -DestinationPath "output/x64/Release/SEOwnedDEx64Release.zip"
 
-      # Step 10: Upload DLL artifact
+      # Step 11: Upload DLL artifact
       - name: Upload DLL artifact
         uses: actions/upload-artifact@v3
         with:
